#define COMP_CONT(REG) \
if (GETLABEL(REG) == _ENTRY_1) \
goto ENTRY_1; \
if (GETLABEL(REG) == _AFTER_LAMBDA_2) \
goto AFTER_LAMBDA_2; \
if (GETLABEL(REG) == _PRIMITIVE_3) \
goto PRIMITIVE_3; \
if (GETLABEL(REG) == _COMPILED_4) \
goto COMPILED_4; \
if (GETLABEL(REG) == _AFTER_CALL_5) \
goto AFTER_CALL_5; \
if (GETLABEL(REG) == _ENTRY_6) \
goto ENTRY_6; \
if (GETLABEL(REG) == _AFTER_LAMBDA_7) \
goto AFTER_LAMBDA_7; \
if (GETLABEL(REG) == _PRIMITIVE_8) \
goto PRIMITIVE_8; \
if (GETLABEL(REG) == _COMPILED_9) \
goto COMPILED_9; \
if (GETLABEL(REG) == _AFTER_CALL_10) \
goto AFTER_CALL_10; \
if (GETLABEL(REG) == _ENTRY_11) \
goto ENTRY_11; \
if (GETLABEL(REG) == _AFTER_LAMBDA_12) \
goto AFTER_LAMBDA_12; \
if (GETLABEL(REG) == _PRIMITIVE_13) \
goto PRIMITIVE_13; \
if (GETLABEL(REG) == _COMPILED_14) \
goto COMPILED_14; \
if (GETLABEL(REG) == _AFTER_CALL_15) \
goto AFTER_CALL_15; \
if (GETLABEL(REG) == _ENTRY_16) \
goto ENTRY_16; \
if (GETLABEL(REG) == _AFTER_LAMBDA_17) \
goto AFTER_LAMBDA_17; \
if (GETLABEL(REG) == _TRUE_BRANCH_18) \
goto TRUE_BRANCH_18; \
if (GETLABEL(REG) == _FALSE_BRANCH_19) \
goto FALSE_BRANCH_19; \
if (GETLABEL(REG) == _AFTER_IF_20) \
goto AFTER_IF_20; \
if (GETLABEL(REG) == _PRIMITIVE_21) \
goto PRIMITIVE_21; \
if (GETLABEL(REG) == _COMPILED_22) \
goto COMPILED_22; \
if (GETLABEL(REG) == _AFTER_CALL_23) \
goto AFTER_CALL_23; \
if (GETLABEL(REG) == _PRIMITIVE_24) \
goto PRIMITIVE_24; \
if (GETLABEL(REG) == _COMPILED_25) \
goto COMPILED_25; \
if (GETLABEL(REG) == _AFTER_CALL_26) \
goto AFTER_CALL_26; \
if (GETLABEL(REG) == _PRIMITIVE_27) \
goto PRIMITIVE_27; \
if (GETLABEL(REG) == _COMPILED_28) \
goto COMPILED_28; \
if (GETLABEL(REG) == _AFTER_CALL_29) \
goto AFTER_CALL_29; \
if (GETLABEL(REG) == _PRIMITIVE_30) \
goto PRIMITIVE_30; \
if (GETLABEL(REG) == _COMPILED_31) \
goto COMPILED_31; \
if (GETLABEL(REG) == _AFTER_CALL_32) \
goto AFTER_CALL_32; \
if (GETLABEL(REG) == _ENTRY_33) \
goto ENTRY_33; \
if (GETLABEL(REG) == _AFTER_LAMBDA_34) \
goto AFTER_LAMBDA_34; \
if (GETLABEL(REG) == _TRUE_BRANCH_35) \
goto TRUE_BRANCH_35; \
if (GETLABEL(REG) == _FALSE_BRANCH_36) \
goto FALSE_BRANCH_36; \
if (GETLABEL(REG) == _AFTER_IF_37) \
goto AFTER_IF_37; \
if (GETLABEL(REG) == _PRIMITIVE_38) \
goto PRIMITIVE_38; \
if (GETLABEL(REG) == _COMPILED_39) \
goto COMPILED_39; \
if (GETLABEL(REG) == _AFTER_CALL_40) \
goto AFTER_CALL_40; \
if (GETLABEL(REG) == _PRIMITIVE_41) \
goto PRIMITIVE_41; \
if (GETLABEL(REG) == _COMPILED_42) \
goto COMPILED_42; \
if (GETLABEL(REG) == _AFTER_CALL_43) \
goto AFTER_CALL_43; \
if (GETLABEL(REG) == _PRIMITIVE_44) \
goto PRIMITIVE_44; \
if (GETLABEL(REG) == _COMPILED_45) \
goto COMPILED_45; \
if (GETLABEL(REG) == _AFTER_CALL_46) \
goto AFTER_CALL_46; \
if (GETLABEL(REG) == _PRIMITIVE_47) \
goto PRIMITIVE_47; \
if (GETLABEL(REG) == _COMPILED_48) \
goto COMPILED_48; \
if (GETLABEL(REG) == _AFTER_CALL_49) \
goto AFTER_CALL_49; \
if (GETLABEL(REG) == _PRIMITIVE_50) \
goto PRIMITIVE_50; \
if (GETLABEL(REG) == _COMPILED_51) \
goto COMPILED_51; \
if (GETLABEL(REG) == _AFTER_CALL_52) \
goto AFTER_CALL_52; \
if (GETLABEL(REG) == _ENTRY_53) \
goto ENTRY_53; \
if (GETLABEL(REG) == _AFTER_LAMBDA_54) \
goto AFTER_LAMBDA_54; \
if (GETLABEL(REG) == _TRUE_BRANCH_55) \
goto TRUE_BRANCH_55; \
if (GETLABEL(REG) == _FALSE_BRANCH_56) \
goto FALSE_BRANCH_56; \
if (GETLABEL(REG) == _AFTER_IF_57) \
goto AFTER_IF_57; \
if (GETLABEL(REG) == _PRIMITIVE_58) \
goto PRIMITIVE_58; \
if (GETLABEL(REG) == _COMPILED_59) \
goto COMPILED_59; \
if (GETLABEL(REG) == _AFTER_CALL_60) \
goto AFTER_CALL_60; \
if (GETLABEL(REG) == _PRIMITIVE_61) \
goto PRIMITIVE_61; \
if (GETLABEL(REG) == _COMPILED_62) \
goto COMPILED_62; \
if (GETLABEL(REG) == _AFTER_CALL_63) \
goto AFTER_CALL_63; \
if (GETLABEL(REG) == _PRIMITIVE_64) \
goto PRIMITIVE_64; \
if (GETLABEL(REG) == _COMPILED_65) \
goto COMPILED_65; \
if (GETLABEL(REG) == _AFTER_CALL_66) \
goto AFTER_CALL_66; \
if (GETLABEL(REG) == _PRIMITIVE_67) \
goto PRIMITIVE_67; \
if (GETLABEL(REG) == _COMPILED_68) \
goto COMPILED_68; \
if (GETLABEL(REG) == _AFTER_CALL_69) \
goto AFTER_CALL_69; \
if (GETLABEL(REG) == _PRIMITIVE_70) \
goto PRIMITIVE_70; \
if (GETLABEL(REG) == _COMPILED_71) \
goto COMPILED_71; \
if (GETLABEL(REG) == _AFTER_CALL_72) \
goto AFTER_CALL_72; \
if (GETLABEL(REG) == _ENTRY_73) \
goto ENTRY_73; \
if (GETLABEL(REG) == _AFTER_LAMBDA_74) \
goto AFTER_LAMBDA_74; \
if (GETLABEL(REG) == _TRUE_BRANCH_75) \
goto TRUE_BRANCH_75; \
if (GETLABEL(REG) == _FALSE_BRANCH_76) \
goto FALSE_BRANCH_76; \
if (GETLABEL(REG) == _AFTER_IF_77) \
goto AFTER_IF_77; \
if (GETLABEL(REG) == _PRIMITIVE_78) \
goto PRIMITIVE_78; \
if (GETLABEL(REG) == _COMPILED_79) \
goto COMPILED_79; \
if (GETLABEL(REG) == _AFTER_CALL_80) \
goto AFTER_CALL_80; \
if (GETLABEL(REG) == _PRIMITIVE_81) \
goto PRIMITIVE_81; \
if (GETLABEL(REG) == _COMPILED_82) \
goto COMPILED_82; \
if (GETLABEL(REG) == _AFTER_CALL_83) \
goto AFTER_CALL_83; \
if (GETLABEL(REG) == _PRIMITIVE_84) \
goto PRIMITIVE_84; \
if (GETLABEL(REG) == _COMPILED_85) \
goto COMPILED_85; \
if (GETLABEL(REG) == _AFTER_CALL_86) \
goto AFTER_CALL_86; \
if (GETLABEL(REG) == _PRIMITIVE_87) \
goto PRIMITIVE_87; \
if (GETLABEL(REG) == _COMPILED_88) \
goto COMPILED_88; \
if (GETLABEL(REG) == _AFTER_CALL_89) \
goto AFTER_CALL_89; \
if (GETLABEL(REG) == _ENTRY_90) \
goto ENTRY_90; \
if (GETLABEL(REG) == _AFTER_LAMBDA_91) \
goto AFTER_LAMBDA_91; \
if (GETLABEL(REG) == _ENTRY_92) \
goto ENTRY_92; \
if (GETLABEL(REG) == _AFTER_LAMBDA_93) \
goto AFTER_LAMBDA_93; \
if (GETLABEL(REG) == _TRUE_BRANCH_94) \
goto TRUE_BRANCH_94; \
if (GETLABEL(REG) == _FALSE_BRANCH_95) \
goto FALSE_BRANCH_95; \
if (GETLABEL(REG) == _AFTER_IF_96) \
goto AFTER_IF_96; \
if (GETLABEL(REG) == _PRIMITIVE_97) \
goto PRIMITIVE_97; \
if (GETLABEL(REG) == _COMPILED_98) \
goto COMPILED_98; \
if (GETLABEL(REG) == _AFTER_CALL_99) \
goto AFTER_CALL_99; \
if (GETLABEL(REG) == _PRIMITIVE_100) \
goto PRIMITIVE_100; \
if (GETLABEL(REG) == _COMPILED_101) \
goto COMPILED_101; \
if (GETLABEL(REG) == _AFTER_CALL_102) \
goto AFTER_CALL_102; \
if (GETLABEL(REG) == _PRIMITIVE_103) \
goto PRIMITIVE_103; \
if (GETLABEL(REG) == _COMPILED_104) \
goto COMPILED_104; \
if (GETLABEL(REG) == _AFTER_CALL_105) \
goto AFTER_CALL_105; \
if (GETLABEL(REG) == _PRIMITIVE_106) \
goto PRIMITIVE_106; \
if (GETLABEL(REG) == _COMPILED_107) \
goto COMPILED_107; \
if (GETLABEL(REG) == _AFTER_CALL_108) \
goto AFTER_CALL_108; \
if (GETLABEL(REG) == _PRIMITIVE_109) \
goto PRIMITIVE_109; \
if (GETLABEL(REG) == _COMPILED_110) \
goto COMPILED_110; \
if (GETLABEL(REG) == _AFTER_CALL_111) \
goto AFTER_CALL_111; \
if (GETLABEL(REG) == _ENTRY_112) \
goto ENTRY_112; \
if (GETLABEL(REG) == _AFTER_LAMBDA_113) \
goto AFTER_LAMBDA_113; \
if (GETLABEL(REG) == _TRUE_BRANCH_114) \
goto TRUE_BRANCH_114; \
if (GETLABEL(REG) == _FALSE_BRANCH_115) \
goto FALSE_BRANCH_115; \
if (GETLABEL(REG) == _AFTER_IF_116) \
goto AFTER_IF_116; \
if (GETLABEL(REG) == _TRUE_BRANCH_117) \
goto TRUE_BRANCH_117; \
if (GETLABEL(REG) == _FALSE_BRANCH_118) \
goto FALSE_BRANCH_118; \
if (GETLABEL(REG) == _AFTER_IF_119) \
goto AFTER_IF_119; \
if (GETLABEL(REG) == _PRIMITIVE_120) \
goto PRIMITIVE_120; \
if (GETLABEL(REG) == _COMPILED_121) \
goto COMPILED_121; \
if (GETLABEL(REG) == _AFTER_CALL_122) \
goto AFTER_CALL_122; \
if (GETLABEL(REG) == _TRUE_BRANCH_123) \
goto TRUE_BRANCH_123; \
if (GETLABEL(REG) == _FALSE_BRANCH_124) \
goto FALSE_BRANCH_124; \
if (GETLABEL(REG) == _AFTER_IF_125) \
goto AFTER_IF_125; \
if (GETLABEL(REG) == _PRIMITIVE_126) \
goto PRIMITIVE_126; \
if (GETLABEL(REG) == _COMPILED_127) \
goto COMPILED_127; \
if (GETLABEL(REG) == _AFTER_CALL_128) \
goto AFTER_CALL_128; \
if (GETLABEL(REG) == _PRIMITIVE_129) \
goto PRIMITIVE_129; \
if (GETLABEL(REG) == _COMPILED_130) \
goto COMPILED_130; \
if (GETLABEL(REG) == _AFTER_CALL_131) \
goto AFTER_CALL_131; \
if (GETLABEL(REG) == _PRIMITIVE_132) \
goto PRIMITIVE_132; \
if (GETLABEL(REG) == _COMPILED_133) \
goto COMPILED_133; \
if (GETLABEL(REG) == _AFTER_CALL_134) \
goto AFTER_CALL_134; \
if (GETLABEL(REG) == _PRIMITIVE_135) \
goto PRIMITIVE_135; \
if (GETLABEL(REG) == _COMPILED_136) \
goto COMPILED_136; \
if (GETLABEL(REG) == _AFTER_CALL_137) \
goto AFTER_CALL_137; \
if (GETLABEL(REG) == _PRIMITIVE_138) \
goto PRIMITIVE_138; \
if (GETLABEL(REG) == _COMPILED_139) \
goto COMPILED_139; \
if (GETLABEL(REG) == _AFTER_CALL_140) \
goto AFTER_CALL_140; \
if (GETLABEL(REG) == _PRIMITIVE_141) \
goto PRIMITIVE_141; \
if (GETLABEL(REG) == _COMPILED_142) \
goto COMPILED_142; \
if (GETLABEL(REG) == _AFTER_CALL_143) \
goto AFTER_CALL_143; \
if (GETLABEL(REG) == _ENTRY_144) \
goto ENTRY_144; \
if (GETLABEL(REG) == _AFTER_LAMBDA_145) \
goto AFTER_LAMBDA_145; \
if (GETLABEL(REG) == _ENTRY_146) \
goto ENTRY_146; \
if (GETLABEL(REG) == _AFTER_LAMBDA_147) \
goto AFTER_LAMBDA_147; \
if (GETLABEL(REG) == _TRUE_BRANCH_148) \
goto TRUE_BRANCH_148; \
if (GETLABEL(REG) == _FALSE_BRANCH_149) \
goto FALSE_BRANCH_149; \
if (GETLABEL(REG) == _AFTER_IF_150) \
goto AFTER_IF_150; \
if (GETLABEL(REG) == _PRIMITIVE_151) \
goto PRIMITIVE_151; \
if (GETLABEL(REG) == _COMPILED_152) \
goto COMPILED_152; \
if (GETLABEL(REG) == _AFTER_CALL_153) \
goto AFTER_CALL_153; \
if (GETLABEL(REG) == _PRIMITIVE_154) \
goto PRIMITIVE_154; \
if (GETLABEL(REG) == _COMPILED_155) \
goto COMPILED_155; \
if (GETLABEL(REG) == _AFTER_CALL_156) \
goto AFTER_CALL_156; \
if (GETLABEL(REG) == _PRIMITIVE_157) \
goto PRIMITIVE_157; \
if (GETLABEL(REG) == _COMPILED_158) \
goto COMPILED_158; \
if (GETLABEL(REG) == _AFTER_CALL_159) \
goto AFTER_CALL_159; \
if (GETLABEL(REG) == _PRIMITIVE_160) \
goto PRIMITIVE_160; \
if (GETLABEL(REG) == _COMPILED_161) \
goto COMPILED_161; \
if (GETLABEL(REG) == _AFTER_CALL_162) \
goto AFTER_CALL_162; \
if (GETLABEL(REG) == _PRIMITIVE_163) \
goto PRIMITIVE_163; \
if (GETLABEL(REG) == _COMPILED_164) \
goto COMPILED_164; \
if (GETLABEL(REG) == _AFTER_CALL_165) \
goto AFTER_CALL_165; \
if (GETLABEL(REG) == _ENTRY_166) \
goto ENTRY_166; \
if (GETLABEL(REG) == _AFTER_LAMBDA_167) \
goto AFTER_LAMBDA_167; \
if (GETLABEL(REG) == _ENTRY_168) \
goto ENTRY_168; \
if (GETLABEL(REG) == _AFTER_LAMBDA_169) \
goto AFTER_LAMBDA_169; \
if (GETLABEL(REG) == _PRIMITIVE_170) \
goto PRIMITIVE_170; \
if (GETLABEL(REG) == _COMPILED_171) \
goto COMPILED_171; \
if (GETLABEL(REG) == _AFTER_CALL_172) \
goto AFTER_CALL_172; \
if (GETLABEL(REG) == _ENTRY_173) \
goto ENTRY_173; \
if (GETLABEL(REG) == _AFTER_LAMBDA_174) \
goto AFTER_LAMBDA_174; \
if (GETLABEL(REG) == _ENTRY_175) \
goto ENTRY_175; \
if (GETLABEL(REG) == _AFTER_LAMBDA_176) \
goto AFTER_LAMBDA_176; \
if (GETLABEL(REG) == _PRIMITIVE_177) \
goto PRIMITIVE_177; \
if (GETLABEL(REG) == _COMPILED_178) \
goto COMPILED_178; \
if (GETLABEL(REG) == _AFTER_CALL_179) \
goto AFTER_CALL_179; \
if (GETLABEL(REG) == _ENTRY_180) \
goto ENTRY_180; \
if (GETLABEL(REG) == _AFTER_LAMBDA_181) \
goto AFTER_LAMBDA_181; \
if (GETLABEL(REG) == _ENTRY_182) \
goto ENTRY_182; \
if (GETLABEL(REG) == _AFTER_LAMBDA_183) \
goto AFTER_LAMBDA_183; \
if (GETLABEL(REG) == _PRIMITIVE_184) \
goto PRIMITIVE_184; \
if (GETLABEL(REG) == _COMPILED_185) \
goto COMPILED_185; \
if (GETLABEL(REG) == _AFTER_CALL_186) \
goto AFTER_CALL_186; \
if (GETLABEL(REG) == _ENTRY_187) \
goto ENTRY_187; \
if (GETLABEL(REG) == _AFTER_LAMBDA_188) \
goto AFTER_LAMBDA_188; \
if (GETLABEL(REG) == _TRUE_BRANCH_189) \
goto TRUE_BRANCH_189; \
if (GETLABEL(REG) == _FALSE_BRANCH_190) \
goto FALSE_BRANCH_190; \
if (GETLABEL(REG) == _AFTER_IF_191) \
goto AFTER_IF_191; \
if (GETLABEL(REG) == _PRIMITIVE_192) \
goto PRIMITIVE_192; \
if (GETLABEL(REG) == _COMPILED_193) \
goto COMPILED_193; \
if (GETLABEL(REG) == _AFTER_CALL_194) \
goto AFTER_CALL_194; \
if (GETLABEL(REG) == _PRIMITIVE_195) \
goto PRIMITIVE_195; \
if (GETLABEL(REG) == _COMPILED_196) \
goto COMPILED_196; \
if (GETLABEL(REG) == _AFTER_CALL_197) \
goto AFTER_CALL_197; \
if (GETLABEL(REG) == _PRIMITIVE_198) \
goto PRIMITIVE_198; \
if (GETLABEL(REG) == _COMPILED_199) \
goto COMPILED_199; \
if (GETLABEL(REG) == _AFTER_CALL_200) \
goto AFTER_CALL_200; \
if (GETLABEL(REG) == _PRIMITIVE_201) \
goto PRIMITIVE_201; \
if (GETLABEL(REG) == _COMPILED_202) \
goto COMPILED_202; \
if (GETLABEL(REG) == _AFTER_CALL_203) \
goto AFTER_CALL_203; 
